# Generated by Django 5.0.3 on 2024-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='名字')),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员复数',
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbDept',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=10, verbose_name='部门名称')),
                ('dloc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门复数',
                'db_table': 'tb_dept',
                'managed': True,
            },
        ),
    ]
